apiVersion: v1
kind: Secret
metadata:
  name: gcr-json-key
  namespace: travel-planner-agent  # Change to your namespace if needed
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    # You need to create this secret with your GCP service account key
    # Run this command to create it:
    # kubectl create secret docker-registry gcr-json-key \
    #   --docker-server=europe-west4-docker.pkg.dev \
    #   --docker-username=_json_key \
    #   --docker-password="$(cat ~/Documents/Documents-Fedora2025/Google_AI_Studio/GKE/credentials.json)" \
    #   --docker-email=<gmail>
