apiVersion: v1
kind: Secret
metadata:
  name: streamlit-app-secrets
type: Opaque
data:
  # Google AI/Gemini API key for AI functionality
  GOOGLE_API_KEY: ""
  # Serper API key for search functionality
  SERPER_API_KEY: ""
  # OpenWeather API key for weather data
  OPENWEATHER_API_KEY: ""
