apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
  labels:
    app: streamlit-app
spec:
  selector:
    app: streamlit-app
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
  type: LoadBalancer